# Desafio Análise de Dados Indicium

### **1. Configuração de ambiente e carregamento dos dados**
1.1. Caso as bibliotecas *Pandas, Matplotlib, Seaborn* não estejam incluídas na distribuição padrão do Python ou não estejam instaladas localmente, executar o comando pip install + biblioteca. Caso contrário, seguir para a importação

In [31]:
#Importar as bibliotecas (usar comando pip install, caso não estejam instaladas)
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
# Carregar os dados do arquivo ZIP
banvic_data = pd.read_csv('../Projeto/dados/banvic_data/agencias.csv')

In [33]:
# Visualizar as primeiras linhas dos dados
banvic_data.head()

,cod_agencia,nome,endereco,cidade,uf,data_abertura,tipo_agencia
0,7,Agência Digital,"Av. Paulista, 1436 - Cerqueira César, São Paul...",São Paulo,SP,2015-08-01,Digital
1,1,Agência Matriz,"Av. Paulista, 1436 - Cerqueira César, São Paul...",São Paulo,SP,2010-01-01,Física
2,2,Agência Tatuapé,"Praça Sílvio Romero, 158 - Tatuapé, São Paulo ...",São Paulo,SP,2010-06-14,Física
3,3,Agência Campinas,"Av. Francisco Glicério, 895 - Vila Lidia, Camp...",Campinas,SP,2012-03-04,Física
4,4,Agência Osasco,"Av. Antônio Carlos Costa, 1000 - Bela Vista, O...",Osasco,SP,2013-11-06,Física

### **2. Limpeza de Dados**
Verificar e tratar valores ausentes (NaN) com `df.isnull().sum()` e `df.dropna()` ou `df.fillna()`.

O método `dropna()` é usado para remover linhas com valores ausentes e `fillna(0)` para preencher valores ausentes com zero. No caso do presente dataset, não foi necessário, já que não tem objetos nulos.
Os passos vistos até aqui para o primeiro dataset, vão ser replicados para os outros arquivos csv.

In [45]:
# Exibir informações básicas sobre os dados
print("Informações sobre os dados:")
print(banvic_data.info())
#nao tem objetos nulos: 10 entradas, 10 não nulos

Informações sobre os dados:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_agencia    10 non-null     int64
 1   nome           10 non-null     object
 2   endereco       10 non-null     object
 3   cidade         10 non-null     object
 4   uf             10 non-null     object
 5   data_abertura  10 non-null     object
 6   tipo_agencia   10 non-null     object
dtypes: int64(1), object(6)
memory usage: 692.0+ bytes
None

In [35]:
#Verificando a data de abertura das agências
banvic_data['data_abertura']

0    2015-08-01
1    2010-01-01
2    2010-06-14
3    2012-03-04
4    2013-11-06
5    2013-12-01
6    2015-04-01
7    2018-01-09
8    2019-10-09
9    2021-10-09
Name: data_abertura, dtype: object

In [36]:

""" # Converter a coluna 'Data_Abertura_Conta' para o tipo datetime
banvic_data['data_abertura'] = pd.to_datetime(banvic_data['data_abertura'])

# Verificar o tipo de dados após a conversão
print(banvic_data.info())

# Criar o gráfico de dispersão
plt.figure(figsize=(12, 8))
for agencia in banvic_data['nome'].unique():
    data_agencia = banvic_data[banvic_data['nome'] == agencia]['data_abertura']
    plt.plot(data_agencia, [agencia] * len(data_agencia), marker='o', linestyle='', label=f'Agência {agencia}')

plt.title('Abertura de Conta por Agência e ano')
plt.xlabel('Ano abertura')
plt.ylabel('Agência')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show() """

" # Converter a coluna 'Data_Abertura_Conta' para o tipo datetime\nbanvic_data['data_abertura'] = pd.to_datetime(banvic_data['data_abertura'])\n\n# Verificar o tipo de dados após a conversão\nprint(banvic_data.info())\n\n# Criar o gráfico de dispersão\nplt.figure(figsize=(12, 8))\nfor agencia in banvic_data['nome'].unique():\n    data_agencia = banvic_data[banvic_data['nome'] == agencia]['data_abertura']\n    plt.plot(data_agencia, [agencia] * len(data_agencia), marker='o', linestyle='', label=f'Agência {agencia}')\n\nplt.title('Abertura de Conta por Agência e ano')\nplt.xlabel('Ano abertura')\nplt.ylabel('Agência')\nplt.legend()\nplt.grid(True)\nplt.tight_layout()\nplt.show() "

In [38]:
""" # Criar uma lista de dicionários para armazenar os resultados
contas_por_mes = []

# Iterar sobre todos os meses
for mes in range(1, 13):
    contas_mes = banvic_data[banvic_data['data_abertura'].dt.month == mes]
    num_contas_mes = len(contas_mes)
    # Adicionar um dicionário representando uma nova linha à lista
    contas_por_mes.extend([{'Mes': mes, 'Numero_Contas': num_contas_mes}])

# Criar um DataFrame a partir da lista de dicionários
contas_por_mes_df = pd.DataFrame(contas_por_mes)

# Exibir o DataFrame resultante
print(contas_por_mes_df) """

AttributeError: Can only use .dt accessor with datetimelike values

In [39]:
# Carregar os dados do arquivo ZIP
# Certifique-se de extrair o conteúdo do arquivo ZIP antes de executar este script
banvic_data_client = pd.read_csv('../Projeto/dados/banvic_data/clientes.csv')

In [40]:
banvic_data_client.head()

,cod_cliente,primeiro_nome,ultimo_nome,email,tipo_cliente,data_inclusao,cpfcnpj,data_nascimento,endereco,cep
0,28,Sabrina,Dias,moreiraemanuelly@example.org,PF,2017-04-03 16:11:00 UTC,357.081.496-39,2006-08-11,Praia de Duarte Vila Piratininga 81327-166 Fer...,95140-704
1,674,Luiz Felipe,Dias,pedroferreira@example.org,PF,2021-02-10 13:27:00 UTC,085.196.374-93,1995-10-11,"Avenida da Rosa, 654 João Paulo Ii 20295449 Nu...",76516-765
2,693,Renan,Dias,ogomes@example.net,PF,2020-01-21 13:12:00 UTC,783.416.059-10,1948-11-19,Jardim de Rodrigues Ipiranga 14161-477 Duarte ...,51779625
3,743,Clara,Dias,rafaelcorreia@example.org,PF,2019-05-06 11:39:00 UTC,589.237.610-95,1978-01-27,"Colônia Thomas Silva, 9 Tupi B 15771-946 Ferna...",19615792
4,769,André,Dias,danilo33@example.org,PF,2017-01-07 14:53:00 UTC,459.608.721-02,1990-08-25,"Rua Correia, 889 Diamante 59123250 Aragão / RS",01672838

In [41]:
banvic_data_client.info()
#script de limpeza

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cod_cliente      998 non-null    int64
 1   primeiro_nome    998 non-null    object
 2   ultimo_nome      998 non-null    object
 3   email            998 non-null    object
 4   tipo_cliente     998 non-null    object
 5   data_inclusao    998 non-null    object
 6   cpfcnpj          998 non-null    object
 7   data_nascimento  998 non-null    object
 8   endereco         998 non-null    object
 9   cep              998 non-null    object
dtypes: int64(1), object(9)
memory usage: 78.1+ KB

In [43]:
# Converter a coluna 'Data_Abertura_Conta' para o tipo datetime
banvic_data_client['data_inclusao'] = pd.to_datetime(banvic_data_client['data_inclusao'])

# Verificar o tipo de dados após a conversão
print(banvic_data_client.info())

# Criar o gráfico de dispersão
plt.figure(figsize=(12, 8))
for agencia in banvic_data_client['cod_client'].unique():
    data_agencia = banvic_data[banvic_data['cod_client'] == agencia]['data_inclusao']
    plt.plot(data_agencia, [agencia] * len(data_agencia), marker='o', linestyle='', label=f'Agência {agencia}')

plt.title('Abertura de Conta por Agência e ano')
plt.xlabel('Ano abertura')
plt.ylabel('Agência')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cod_cliente      998 non-null    int64
 1   primeiro_nome    998 non-null    object
 2   ultimo_nome      998 non-null    object
 3   email            998 non-null    object
 4   tipo_cliente     998 non-null    object
 5   data_inclusao    998 non-null    datetime64[ns, UTC]
 6   cpfcnpj          998 non-null    object
 7   data_nascimento  998 non-null    object
 8   endereco         998 non-null    object
 9   cep              998 non-null    object
dtypes: datetime64[ns, UTC](1), int64(1), object(8)
memory usage: 78.1+ KB
None

KeyError: 'cod_client'

In [ ]:
#fazer scrip juntar clientes + agencia
código cliente

In [47]:
#Verificando os ceps existentes 
banvic_data_client['cep'].unique()

array(['95140-704', '76516-765', '51779625', '19615792', '01672838',
       '07814-131', '90221-380', '44875-244', '42603-833', '23176352',
       '96027-142', '29942-354', '97628-818', '57113-154', '26119706',
       '80317732', '77226042', '12716-003', '37988-526', '16954952',
       '51092202', '96975888', '73739-486', '50832-820', '77360-182',
       '51214338', '49990438', '84504002', '63158375', '69025958',
       '05254-597', '04065275', '47546-871', '88422-547', '87868-132',
       '67750-393', '30314554', '75462082', '11965-789', '14157-016',
       '26941177', '88078064', '02434042', '25512578', '98200059',
       '31500163', '18876-575', '86294-895', '38071-009', '38180255',
       '89813224', '98259-386', '67484257', '07873-123', '56424-819',
       '81473-142', '19744436', '74907782', '07845-704', '11168371',
       '43803139', '50946020', '37183-556', '03481410', '70396-535',
       '77732-400', '99956563', '43609-121', '25715953', '20775-963',
       '13577256', '31297275', '45442696', '13895327', '27315-383',
       '58899466', '34609558', '92215-516', '85811670', '71253-234',
       '42328-349', '74802-721', '84406630', '04065-364', '32770-840',
       '10559-302', '87182675', '96168071', '23037-823', '76706-799',
       '26839-985', '56682892', '23590-188', '68301-753', '07473442',
       '44978329', '30513678', '88390892', '55776517', '44743727',
       '80918276', '21092961', '84143888', '29563-668', '64841594',
       '06447-430', '20931894', '29074-901', '42839110', '39617502',
       '43287847', '91580-802', '39582-953', '48090-423', '92666276',
       '80881095', '98430781', '14585816', '47534-613', '81853963',
       '06759-880', '93769-315', '06635-669', '30163-306', '05487-000',
       '15103-868', '15799-330', '72785-264', '61967117', '11151018',
       '49973-191', '14310685', '93285-302', '39842-347', '35366-296',
       '65540-758', '37512880', '78125-333', '91403292', '16914199',
       '92524874', '48576950', '29962-922', '17185-932', '22473392',
       '75910470', '94642477', '55592-946', '72526-425', '99049657',
       '15270-670', '10730-212', '76188259', '68650457', '97109620',
       '15071262', '23460-398', '17028-400', '00802-813', '24779-740',
       '50913156', '25306594', '69463-503', '35663647', '18237366',
       '05583827', '50196064', '29201854', '62394839', '97022-268',
       '44030-253', '23047749', '59134843', '03168134', '59192733',
       '06016884', '96570869', '93782-527', '58314-883', '50479649',
       '78584-453', '49504138', '36846-137', '51705023', '29387-861',
       '15590730', '64912-312', '22445-315', '97949-601', '98230-713',
       '17350-278', '84050-003', '69493-799', '95017-932', '26064-419',
       '13709-647', '52737-030', '68408-718', '21494-484', '03740382',
       '19148089', '62871467', '50636-754', '53954-224', '35556-306',
       '74509-994', '58058-025', '39836037', '30186-893', '53456544',
       '80355-665', '59204955', '14500-907', '11019-585', '73671994',
       '77592-484', '68273-210', '78697337', '97477173', '20568868',
       '14677-152', '25788873', '96961992', '04974394', '94645786',
       '71428-512', '70742-709', '64223293', '45708-495', '80623-031',
       '38887-523', '14782-172', '98411-088', '66019018', '26538-781',
       '74975416', '46688811', '21603-931', '00147-561', '49204-295',
       '58446-711', '73121-676', '01609847', '73044-289', '40085637',
       '79919593', '80530791', '86122-560', '97449-955', '81548-188',
       '93994345', '31235095', '48641-854', '22237-337', '42445519',
       '63790069', '50402163', '95198-890', '41597-578', '11833-620',
       '86348520', '53833679', '53337997', '72402214', '66313047',
       '54404420', '46910487', '01888-571', '95294945', '26042844',
       '41039-098', '54585-000', '18419-509', '08164-995', '19166-875',
       '64726243', '77606835', '66905558', '51064-127', '06819237',
       '64098823', '28693764', '35623-437', '76910649', '57735990',
       '30145-805', '85964298', '75465498', '55834-279', '28720-323',
       '05433470', '88407-318', '14947282', '82878539', '18074779',
       '51519-852', '77823-250', '05554873', '97397-921', '37638910',
       '36964637', '98536400', '47471-169', '38555902', '13536663',
       '04783273', '46057-007', '25315-391', '23947-364', '53041258',
       '35253-970', '73186-842', '54416006', '36872-995', '43431-930',
       '72750-274', '58000199', '54951-507', '36001-295', '02265-501',
       '35498603', '78151-537', '95977393', '43688-770', '08093154',
       '81446657', '36567-846', '68473580', '30944-978', '29854724',
       '19613-119', '79765622', '59958-346', '24508-434', '16577479',
       '10322-871', '86050-358', '79107382', '08907828', '48120724',
       '02217-338', '27479-650', '26391863', '18035963', '77067-771',
       '92648022', '20739-657', '37378-687', '88515-404', '04127-343',
       '95011-680', '84829001', '81822-316', '65986-747', '73222953',
       '44399366', '02101-190', '51923031', '19629-983', '35686159',
       '23499-744', '02417-883', '50773-129', '15309-406', '73042220',
       '44099-630', '17775-526', '72543224', '81864640', '55688182',
       '37929375', '33631-389', '55910-812', '76057165', '37436528',
       '02065-237', '01802105', '01651-705', '75949393', '85701095',
       '03071741', '11102-836', '26853-378', '14501-313', '68469-740',
       '47917222', '52803-114', '15984-247', '14038881', '20079-824',
       '50034-079', '03625-157', '08810805', '01900664', '10730371',
       '46894157', '80189860', '17116-057', '94233-086', '56495606',
       '68532-892', '76243-469', '36233255', '01682-762', '25099-614',
       '67467-482', '28587-599', '64341769', '50261-096', '73982-067',
       '98938-535', '94247-539', '91891634', '12180-103', '67594-724',
       '43504963', '25323-209', '77048-875', '79586-846', '57281-793',
       '48898293', '30966-116', '84319-828', '84381061', '61725909',
       '94563-369', '40562934', '81164-915', '20478-520', '60290-611',
       '91014485', '58403-824', '34227301', '90777463', '88489-764',
       '60794-612', '10207922', '29021919', '04554-217', '67892719',
       '01814-432', '93983938', '39587-897', '26119727', '03756332',
       '19720-769', '29456824', '50246702', '90069673', '38755-229',
       '37217800', '50743388', '23882-749', '37884316', '03166-379',
       '59717-836', '22250134', '54516237', '26474200', '36694-446',
       '56676-337', '41121-283', '64483022', '02240596', '72383779',
       '57218048', '58010319', '46872-672', '59657-825', '32199475',
       '95890981', '80456-424', '58065269', '12376047', '93898969',
       '45650110', '10764-469', '29074-591', '13715347', '41703129',
       '66800-272', '26189090', '79261182', '75315066', '61548005',
       '80902-628', '82725835', '52387994', '03233-139', '26574-404',
       '98191742', '11027-566', '60767-792', '10493-845', '83565-860',
       '99161510', '91263340', '59276367', '99555-106', '11243-236',
       '44811-766', '11883-390', '42430-747', '71337392', '83728117',
       '21373248', '38243-006', '51618919', '82355-894', '41812110',
       '08094-852', '99471851', '52389135', '90177-078', '99364-926',
       '54474894', '71436-266', '35352-960', '00506-259', '67600436',
       '86938-977', '71920821', '25372-189', '41060234', '11580065',
       '18306-600', '75390263', '69003-972', '02785728', '13347642',
       '61410-865', '92278668', '03524308', '02181-326', '59625-368',
       '57267113', '93250-071', '72101-372', '17468-663', '47587350',
       '44587-274', '86841-476', '57105-880', '20290-725', '69265010',
       '86720-928', '20921-329', '91322358', '66310967', '15510174',
       '92293551', '42074-019', '43218579', '56335095', '31770-420',
       '04123732', '17882-080', '62436-426', '19130-426', '76013101',
       '88959-636', '60173281', '68219-707', '10183184', '45295-653',
       '62512714', '00427644', '09471122', '20479-151', '07948-351',
       '72098-448', '94558596', '53805660', '25721-707', '10725-665',
       '36206809', '35780004', '13920715', '05790922', '08026207',
       '01697859', '93720793', '63811868', '03412726', '28143660',
       '00167-046', '07616-295', '90281-645', '86635643', '56080861',
       '49009385', '54571-005', '00262-103', '67473094', '08955021',
       '87354941', '75408722', '41520-936', '99572275', '46015684',
       '16347-789', '80883467', '29576719', '80160975', '60976-701',
       '58257-173', '54957-836', '74310977', '00803602', '34847413',
       '69658-168', '09777905', '58063933', '85405-606', '45895-886',
       '32349-572', '34250783', '95211861', '87123267', '62717655',
       '97593-166', '64577-629', '18900-231', '19599-389', '69958-930',
       '02056823', '77481-121', '15155-764', '69843363', '88159-092',
       '21811673', '58926-121', '52359-242', '88852254', '42454829',
       '29896369', '62135759', '04736-349', '12587-908', '87469775',
       '96517-916', '95216172', '20897-575', '72954-765', '46837-336',
       '72048-406', '18233-667', '84431718', '94207716', '68525237',
       '90460-313', '06445-888', '20281879', '08810-467', '00023-304',
       '17288-266', '07027312', '61506780', '44708672', '98105-954',
       '53155-194', '47382-055', '06168-064', '48067-920', '22511466',
       '48430-435', '67309619', '49195976', '09373098', '62782-097',
       '32727103', '69264-380', '69878-651', '80537881', '60556-393',
       '41051300', '77149-544', '62165837', '16431535', '07445060',
       '93532415', '05675-228', '40974811', '19736544', '68814494',
       '86898-227', '45539156', '83642191', '98547-972', '88416-256',
       '63638-761', '56414647', '70976-910', '16889847', '45833752',
       '58810090', '84785-656', '50910135', '29259296', '62913-346',
       '09722268', '40557-484', '46903-963', '70049512', '90910-527',
       '09413343', '55887339', '28353-018', '38080-346', '65236138',
       '87757-995', '94039952', '61531-523', '63143-287', '53746-671',
       '74607057', '18035493', '59981945', '65356037', '68868-878',
       '20114460', '60869553', '21981021', '11658-609', '77289-010',
       '60759944', '44667-028', '26042-921', '53952-163', '26236980',
       '20163-136', '53011234', '19025-885', '14508-865', '54165313',
       '30690903', '58956-583', '42798399', '25244388', '07567278',
       '64342245', '84075350', '99953812', '19905255', '11832-547',
       '26853-361', '64172-961', '76440-267', '63295-939', '94339-803',
       '07428521', '93633-706', '97675-667', '97685445', '12155532',
       '89280-864', '68092-313', '40467-614', '81193-115', '86453320',
       '58661-890', '59633-454', '87506-304', '60999280', '55913-053',
       '90139-977', '12160847', '87901-288', '78398-688', '89964-963',
       '95694-426', '01613203', '45240598', '46469073', '27276817',
       '37113-152', '29657-764', '21601596', '80483580', '29165027',
       '79522419', '59960-080', '34927-035', '69613-287', '05860602',
       '48276-010', '99252052', '61566532', '51218-272', '42069-597',
       '52099-862', '10703-141', '59066-697', '50987-872', '93866-463',
       '67970-617', '44209-089', '39563-033', '10142341', '15723-507',
       '32672164', '39393-555', '44492-634', '96254453', '71158-691',
       '71513521', '02025883', '25765-264', '23978-780', '62560-172',
       '52820470', '90467127', '34143-462', '86541-029', '32056-771',
       '17928-914', '23793323', '15033744', '29819-675', '83270255',
       '46177-965', '00264638', '13700963', '80534-607', '38783875',
       '40294-301', '21837993', '83855198', '80604493', '69346548',
       '51467-373', '06896584', '92971-218', '20530-830', '40899-331',
       '98215323', '34095-618', '30446-154', '52750-511', '36757-275',
       '26342-184', '57749312', '57985897', '38041-732', '87335481',
       '12373200', '98383701', '11452-459', '49032-305', '84921499',
       '14362606', '09304-471', '33421319', '07616-570', '25857675',
       '97402-978', '92815998', '47030105', '75319572', '49961162',
       '06435720', '20597-412', '64285-091', '49502-391', '81600217',
       '63541-173', '09608-657', '13852-001', '78505-017', '05097-896',
       '82212-140', '83576382', '32671-446', '99906-712', '65297-551',
       '26757418', '09963-625', '93842428', '36323-611', '21886579',
       '58836369', '08567273', '55775-046', '58492135', '13306021',
       '95852-485', '15651001', '48804710', '84203-810', '47657-827',
       '77420111', '90446-968', '06282416', '03392871', '06842-404',
       '27901042', '28155450', '57012244', '94005-165', '77061439',
       '05824-490', '83554-241', '82890534', '69614-039', '01623853',
       '12242-958', '91130-743', '67308-317', '19210293', '00215118',
       '29668-757', '64726669', '63949-164', '56004-247', '60379109',
       '17495865', '10973112', '34903-374', '48563-639', '43914-408',
       '42264-376', '99955777', '22647-853', '27706384', '10557-284',
       '79069920', '80368790', '97755-778', '54965-372', '22657-163',
       '71829-681', '20679-948', '97811-552', '55858-197', '59101561',
       '26812-022', '50116-459', '26806-550', '60188-798', '55765-821',
       '39833273', '26418948', '23385183', '30778558', '80854977',
       '88267-114', '49158046', '41606515', '11817-226', '87324-761',
       '72563332', '12331-285', '37186-965', '42099413', '46154-666',
       '27938-464', '90205-329', '27808532', '55263-600', '81315-884',
       '05964-403', '79618894', '25815457', '58701124', '15001-358',
       '57442026', '65755-758', '50201054', '92732966', '51797436',
       '85510-255', '58593-834', '63334006', '85923-196', '88118-294',
       '10958-170', '72930-493', '87493-182', '89659-956', '03366293',
       '06463-522', '98928640', '62039-437', '80497-612', '08342-543',
       '13633730', '72374771', '82998-298', '73849-470', '91422-196',
       '61134-341', '88015872', '75614912', '08264521', '55045-265',
       '88159-361', '36211-005', '15386938'], dtype=object)

In [ ]:
#banvic_data_client['data_abertura']
banvic_data_client['tipo_cliente'].value_counts()

tipo_cliente
PF    998
Name: count, dtype: int64

In [ ]:
banvic_data_contas = pd.read_csv('../Projeto/dados/banvic_data/contas.csv')
banvic_data_contas.head()

,num_conta,cod_cliente,cod_agencia,cod_colaborador,tipo_conta,data_abertura,saldo_total,saldo_disponivel,data_ultimo_lancamento
0,53,53,1,7,PF,2011-05-24 15:30:00 UTC,2984.7615,2814.67,2019-07-02 11:03:46 UTC
1,190,190,1,7,PF,2014-10-17 14:48:00 UTC,4262.4322,4191.86,2021-03-25 12:00:15 UTC
2,191,191,1,7,PF,2013-03-23 14:14:00 UTC,3266.5680,3080.71,2016-09-09 23:34:15 UTC
3,203,203,1,7,PF,2016-08-03 16:13:00 UTC,21241.5424,19461.56,2022-12-28 07:58:24 UTC
4,254,254,1,7,PF,2012-10-24 13:48:00 UTC,13335.6966,13197.54,2013-12-20 22:20:00 UTC

In [ ]:
#verificando quantas contas abertas temos em cada agencia
banvic_data_contas['cod_agencia'].value_counts()

cod_agencia
7     460
1     119
2     101
3      76
4      65
5      61
6      52
8      30
9      30
10      5
Name: count, dtype: int64

In [44]:
tabela_final_df = pd.merge(banvic_data_contas[['cod_agencia', 'cod_cliente', 'data_abertura']], 
                           banvic_data[['cod_agencia']], 
                           on='cod_agencia', 
                           how='inner')

print(tabela_final_df)

     cod_agencia  cod_cliente            data_abertura
0              1           53  2011-05-24 15:30:00 UTC
1              1          190  2014-10-17 14:48:00 UTC
2              1          191  2013-03-23 14:14:00 UTC
3              1          203  2016-08-03 16:13:00 UTC
4              1          254  2012-10-24 13:48:00 UTC
..           ...          ...                      ...
994           10          466  2022-10-26 14:13:00 UTC
995           10          764  2022-09-08 11:06:00 UTC
996           10          488  2022-07-16 10:16:00 UTC
997           10          395  2022-12-01 15:27:00 UTC
998           10          355  2022-10-22 14:50:00 UTC

[999 rows x 3 columns]

In [ ]:
banvic_data_contas['data_abertura']